/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sejun.work;

import java.util.Scanner;

public class App {
	static class Point {
		int x;
		int y;
	}
	final static int N = 10;
	static Point[] st = new Point[N];
	static Point[] ed = new Point[N];
	static int count = 0;

    public static void main(String[] args) {
    	getstPoint();
    	
    	for (int i = 0; i < count; i++) {
    		Point p = new Point();
    		p = st[i];
    		System.out.printf("x : %d y : %d", p.x, p.y);
    	}
    	System.out.println();
    	
    }

	static void getstPoint() {
		Scanner sc = new Scanner(System.in);
		for(int i = 0; i < N; i++) {
			count++;
			Point p = new Point();
			
			System.out.print("start x 값 :");
			p.x = sc.nextInt();
			sc.nextLine();
			
			System.out.print("start y 값 : ");
			p.y = sc.nextInt();
			sc.nextLine();
			
			st[i] = p;
			
			System.out.print("계속 입력하시겠습니까");
			String response = sc.nextLine();
			if (!response.equalsIgnoreCase("y")) {
				sc.close();
				break;
			}
			
		}
	
	}
	

}

